# La directiva version se considera obsoleta
# version: '3'
# version: '3.8'
# Definimos una aplicación con 2 servicios (microservicios): Nuestra aplicación PHP y MariaDB.
services: 
# Servicio 1: aplicación CRUD dockerizada. Utiliza la imagen construida en la fase de desarrollo : lumigv/lamp-crud-app:latest
  apache-php-crud:
    image: ygutierrezm05/actividad61-aplicacion-crud-php:latest
    ports: 
      - 8080:80
    environment: 
      - MARIADB_HOST=mariadb
      - MARIADB_DATABASE=${DATABASE}
      - MARIADB_USER=${USERNAME}
      - MARIADB_PASSWORD=${PASSWORD}  
# Controla el orden inicio de los servicios      
    depends_on:
      - db
# Definimos una política de reinicio del servicio: el contenedor se reinicia cada vez que se detiene por cualquier motivo, excepto cuando se detiene de forma manual (explícita)
# Recomendable en entornos de producción en un único servidor.
    restart: always      

# Servicio 2: mariadb 
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment: 
# El acceso a las variables de entorno puede ser de dos maneras: $DATABASE ó ${DATABASE} utilizan el valor de la variable DATABASE definida en el archivo .env
      - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MARIADB_DATABASE=${DATABASE}
      - MARIADB_USER=${USERNAME}
      - MARIADB_PASSWORD=${PASSWORD}
      - LANG=C.UTF-8
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d 
    restart: always
# Definimos los volúmenes
volumes:
  mariadb_data:

  
