name: CI/CD Pipeline - CRUD PHP

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build de la imagen
        run: docker build -t ${{ secrets.DOCKER_USER }}/crud-php:latest .

      - name: Push a DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/crud-php:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Despliegue en AWS mediante SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Parar el contenedor anterior si existe
            sudo docker stop crud-app || true
            sudo docker rm crud-app || true
            # Limpiar imágenes antiguas para no llenar el disco
            sudo docker image prune -f
            # Descarga de la nueva imagen (PULL)
            sudo docker pull ${{ secrets.DOCKER_USER }}/crud-php:latest
            # Ejecución (RUN) - Recuerda usar el puerto 8080 que configuramos para el Proxy
            sudo docker run -d --name crud-app -p 8080:80 ${{ secrets.DOCKER_USER }}/crud-php:latest